import { useState } from "react";
import { WorkbenchShell } from "../components/WorkbenchShell";
import { DEFAULT_PREFERENCES, type Density, type MotionMode } from "../lib/workspace";
import type { MarketplaceView } from "../lib/marketplace";
import { useWorkspace } from "../state/WorkspaceContext";
import "../styles/marketplace.css";

function Choice<T extends string>({ value, values, onChange }: { value: T; values: readonly T[]; onChange: (value: T) => void }) {
  return <div className="setting-choice">{values.map(item => <button key={item} type="button" className={value === item ? "active" : ""} aria-pressed={value === item} onClick={() => onChange(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div>;
}

export function SettingsPage() {
  const { preferences, collections, updatePreferences, restorePreferences, clearCollections } = useWorkspace();
  const [confirmClear, setConfirmClear] = useState(false);
  return <WorkbenchShell className="workspace-content-page settings-page"><header className="workspace-page-header settings-header"><span>WORKSPACE CONTROL</span><h1>Settings</h1><p>Set how the catalog opens, how much information it shows, and how the details workspace moves.</p><div className="settings-local-note">Saved in this browser · {collections.length} personal collection{collections.length === 1 ? "" : "s"}</div></header><div className="workspace-page-scroll settings-grid">
    <section className="settings-card"><div className="settings-card-heading"><span>01</span><div><h2>Browsing</h2><p>Choose the default catalog presentation.</p></div></div><label><span>Default Marketplace view<small>Used only when the URL has no explicit view.</small></span><Choice value={preferences.defaultView} values={["cards", "table", "gallery"] as MarketplaceView[]} onChange={defaultView => updatePreferences({ defaultView })}/></label><label><span>Result density<small>Compact fits more results into the workbench.</small></span><Choice value={preferences.density} values={["comfortable", "compact"] as Density[]} onChange={density => updatePreferences({ density })}/></label></section>
    <section className="settings-card"><div className="settings-card-heading"><span>02</span><div><h2>Details workspace</h2><p>Control the default split and keyboard behavior.</p></div></div><label><span>Repository width<small>{preferences.splitRatio}% repository · {100 - preferences.splitRatio}% details</small></span><input type="range" min="40" max="70" value={preferences.splitRatio} onChange={event => updatePreferences({ splitRatio: Number(event.target.value) })}/></label><label className="setting-toggle"><span>Remember resized panel width<small>Use the last dragged ratio on the next visit.</small></span><input type="checkbox" checked={preferences.rememberSplitRatio} onChange={event => updatePreferences({ rememberSplitRatio: event.target.checked })}/></label><label className="setting-toggle"><span>Focus details after opening<small>Moves keyboard focus to the detail panel.</small></span><input type="checkbox" checked={preferences.focusDetails} onChange={event => updatePreferences({ focusDetails: event.target.checked })}/></label></section>
    <section className="settings-card"><div className="settings-card-heading"><span>03</span><div><h2>Motion</h2><p>Match the workbench movement to your preference.</p></div></div><label><span>Animation mode<small>System follows the device reduced-motion setting.</small></span><Choice value={preferences.motion} values={["system", "full", "reduced"] as MotionMode[]} onChange={motion => updatePreferences({ motion })}/></label><div className={`motion-preview motion-${preferences.motion}`}><i/><span>Detail panel preview</span></div></section>
    <section className="settings-card settings-danger"><div className="settings-card-heading"><span>04</span><div><h2>Local data</h2><p>Reset preferences separately from personal collections.</p></div></div><div className="settings-actions"><button type="button" onClick={restorePreferences}>Restore defaults</button>{confirmClear ? <div className="inline-confirm"><span>Clear {collections.length} collections?</span><button onClick={() => { clearCollections(); setConfirmClear(false); }}>Clear now</button><button onClick={() => setConfirmClear(false)}>Cancel</button></div> : <button type="button" className="danger-button" disabled={!collections.length} onClick={() => setConfirmClear(true)}>Clear personal collections</button>}</div><small>Default split ratio is {DEFAULT_PREFERENCES.splitRatio}%.</small></section>
  </div></WorkbenchShell>;
}
